// version.h
#define FILE_VERSION_MAJOR    1
#define FILE_VERSION_MINOR    1
#define FILE_VERSION_BUILD    0
#define FILE_VERSION_REVISION 0

#define FILE_VERSION_NUMS     FILE_VERSION_MAJOR,FILE_VERSION_MINOR,FILE_VERSION_BUILD,FILE_VERSION_REVISION
#define FILE_VERSION_STRING   FILE_VERSION_MAJOR.FILE_VERSION_MINOR.FILE_VERSION_BUILD.FILE_VERSION_REVISION

#define MAKESTRING(x) #x
#define VERSION_STRING(a,b,c,d) MAKESTRING(a.b.c.d)
